# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

---
release_tags: &release_tags
  tags:
    only: /^v\d+(\.\d+){2}(-.*)?$/

version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run:
          name: Install modules and dependencies.
          command: npm install
      - run:
          name: Run unit tests.
          command: npm run test
      - run:
          name: Submit coverage data to codecov.
          command: npm run codecov
          when: always
